name: build_and_test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test ${{ matrix.os }} - ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mobie
          mamba-version: "*"
          auto-update-conda: true
          environment-file: environment.yaml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Install package
        shell: bash -l {0}
        run: pip install -e .

      - name: Run tests
        shell: bash -l {0}
        run: python -m unittest discover -s test -v
